<?php

use CodeIgniter\Router\RouteCollection;

/** @var RouteCollection $routes */
$routes->get('/', 'Home::index');
$routes->get('login', 'Auth::login');
$routes->post('login', 'Auth::attempt');
$routes->get('logout', 'Auth::logout');
$routes->get('dashboard/logout', 'Auth::logout');
$routes->get('home/change_lang/(:segment)', 'Home::changeLang/$1');
$routes->get('home/faq', 'Home::faq');
$routes->get('home/privacy_policy', 'Home::privacyPolicy');
$routes->get('dashboard', 'Dashboard::index', ['filter' => 'auth']);
$routes->get('dashboard/profile/setting', 'Dashboard::profileSetting', ['filter' => 'auth']);
$routes->post('dashboard/profile/setting', 'Dashboard::updateProfile', ['filter' => 'auth']);
$routes->get('dashboard/profile', 'Dashboard::profileSetting', ['filter' => 'auth']);
$routes->get('dashboard/change_pass', 'Dashboard::changePassword', ['filter' => 'auth']);
$routes->post('dashboard/change_pass', 'Dashboard::updatePassword', ['filter' => 'auth']);
$routes->get('dashboard/notifications/(:num)/open', 'Dashboard::openNotification/$1', ['filter' => 'auth']);
$routes->post('dashboard/notifications/read-all', 'Dashboard::markAllNotificationsRead', ['filter' => 'auth']);
$routes->post('dashboard/approvals/courses/(:num)', 'Dashboard::decideCourseApproval/$1', ['filter' => 'auth']);
$routes->post('dashboard/approvals/surveys/(:num)', 'Dashboard::decideSurveyApproval/$1', ['filter' => 'auth']);
$routes->post('dashboard/approvals/course-groups/(:num)', 'Dashboard::decideCourseGroupApproval/$1', ['filter' => 'auth']);
$routes->post('dashboard/approvals/bulk', 'Dashboard::decideBulkApprovals', ['filter' => 'auth']);
$routes->get('dashboard/profile/certificate', 'CertificatePortal::index', ['filter' => 'auth']);
$routes->get('migration/status', 'MigrationStatus::index', ['filter' => 'auth']);
$routes->get('manage_courses', 'CoursePortal::manageHome', ['filter' => 'auth']);
$routes->get('course', 'CoursePortal::learningHome', ['filter' => 'auth']);
$routes->get('managecourse/course_groups', 'CoursePortal::courseGroups', ['filter' => 'auth']);
$routes->post('managecourse/course_groups/create', 'CoursePortal::storeCourseGroup', ['filter' => 'auth']);
$routes->post('managecourse/course_groups/(:num)/update', 'CoursePortal::updateCourseGroup/$1', ['filter' => 'auth']);
$routes->post('managecourse/course_groups/(:num)/status', 'CoursePortal::courseGroupStatus/$1', ['filter' => 'auth']);
$routes->post('managecourse/course_groups/(:num)/approval', 'CoursePortal::courseGroupApproval/$1', ['filter' => 'auth']);
$routes->post('managecourse/course_groups/(:num)/archive', 'CoursePortal::archiveCourseGroup/$1', ['filter' => 'auth']);
$routes->get('managecourse/courses_all', 'CoursePortal::manageCourses', ['filter' => 'auth']);
$routes->get('managecourse/courses_all/create', 'CoursePortal::createCourse', ['filter' => 'auth']);
$routes->post('managecourse/courses_all/create', 'CoursePortal::storeCourse', ['filter' => 'auth']);
$routes->get('managecourse/courses_all/(:num)/edit', 'CoursePortal::editCourse/$1', ['filter' => 'auth']);
$routes->post('managecourse/courses_all/(:num)/update', 'CoursePortal::updateCourse/$1', ['filter' => 'auth']);
$routes->post('managecourse/courses_all/(:num)/status', 'CoursePortal::courseStatus/$1', ['filter' => 'auth']);
$routes->post('managecourse/courses_all/(:num)/groups/update', 'CoursePortal::updateCourseGroups/$1', ['filter' => 'auth']);
$routes->get('managecourse/course_notifications', 'CoursePortal::notificationLogs', ['filter' => 'auth']);
$routes->post('managecourse/course_notifications/(:num)/retry', 'CoursePortal::retryNotificationSchedule/$1', ['filter' => 'auth']);
$routes->get('managecourse/course_notification_audience', 'CoursePortal::audienceOptions', ['filter' => 'auth']);
$routes->get('managecourse/courses_all/(:num)/lessons/create', 'CoursePortal::createLesson/$1', ['filter' => 'auth']);
$routes->post('managecourse/courses_all/(:num)/lessons/create', 'CoursePortal::storeLesson/$1', ['filter' => 'auth']);
$routes->get('managecourse/lessons/(:num)/edit', 'CoursePortal::editLesson/$1', ['filter' => 'auth']);
$routes->post('managecourse/lessons/(:num)/update', 'CoursePortal::updateLesson/$1', ['filter' => 'auth']);
$routes->post('managecourse/lessons/(:num)/status', 'CoursePortal::lessonStatus/$1', ['filter' => 'auth']);
$routes->post('managecourse/lessons/(:num)/media/create', 'CoursePortal::saveLessonMedia/$1', ['filter' => 'auth']);
$routes->post('managecourse/media/(:num)/update', 'CoursePortal::updateLessonMedia/$1', ['filter' => 'auth']);
$routes->post('managecourse/lessons/(:num)/documents/create', 'CoursePortal::saveLessonDocument/$1', ['filter' => 'auth']);
$routes->post('managecourse/documents/(:num)/update', 'CoursePortal::updateLessonDocument/$1', ['filter' => 'auth']);
$routes->post('managecourse/lessons/(:num)/scorm/save', 'CoursePortal::saveLessonScorm/$1', ['filter' => 'auth']);
$routes->get('managecourse/quizzes', 'QuizPortal::manage', ['filter' => 'auth']);
$routes->get('managecourse/quizzes/import-template', 'QuizPortal::importTemplate', ['filter' => 'auth']);
$routes->get('managecourse/quizzes/create', 'QuizPortal::create', ['filter' => 'auth']);
$routes->post('managecourse/quizzes/create', 'QuizPortal::store', ['filter' => 'auth']);
$routes->get('managecourse/quizzes/(:num)/edit', 'QuizPortal::edit/$1', ['filter' => 'auth']);
$routes->post('managecourse/quizzes/(:num)/update', 'QuizPortal::update/$1', ['filter' => 'auth']);
$routes->post('managecourse/quizzes/(:num)/status', 'QuizPortal::status/$1', ['filter' => 'auth']);
$routes->post('managecourse/quizzes/(:num)/questions/create', 'QuizPortal::storeQuestion/$1', ['filter' => 'auth']);
$routes->post('managecourse/quizzes/(:num)/questions/import', 'QuizPortal::importQuestions/$1', ['filter' => 'auth']);
$routes->post('managecourse/quiz-questions/(:num)/update', 'QuizPortal::updateQuestion/$1', ['filter' => 'auth']);
$routes->post('managecourse/quiz-questions/(:num)/status', 'QuizPortal::questionStatus/$1', ['filter' => 'auth']);
$routes->get('managecourse/quizzes/(:num)/grading', 'QuizPortal::grading/$1', ['filter' => 'auth']);
$routes->post('managecourse/quiz-answers/(:num)/grade', 'QuizPortal::gradeAnswer/$1', ['filter' => 'auth']);
$routes->get('managecourse/surveys', 'SurveyPortal::manage', ['filter' => 'auth']);
$routes->get('managecourse/surveys/create', 'SurveyPortal::create', ['filter' => 'auth']);
$routes->post('managecourse/surveys/create', 'SurveyPortal::store', ['filter' => 'auth']);
$routes->get('managecourse/surveys/(:num)/edit', 'SurveyPortal::edit/$1', ['filter' => 'auth']);
$routes->post('managecourse/surveys/(:num)/update', 'SurveyPortal::update/$1', ['filter' => 'auth']);
$routes->post('managecourse/surveys/(:num)/status', 'SurveyPortal::status/$1', ['filter' => 'auth']);
$routes->post('managecourse/surveys/(:num)/questions/create', 'SurveyPortal::storeQuestion/$1', ['filter' => 'auth']);
$routes->post('managecourse/survey-questions/(:num)/update', 'SurveyPortal::updateQuestion/$1', ['filter' => 'auth']);
$routes->post('managecourse/survey-questions/(:num)/status', 'SurveyPortal::questionStatus/$1', ['filter' => 'auth']);
$routes->get('managecourse/surveys/(:num)/report', 'SurveyPortal::report/$1', ['filter' => 'auth']);
$routes->get('managecourse/surveys/(:num)/report/export', 'SurveyPortal::exportReport/$1', ['filter' => 'auth']);
$routes->get('coursemain/all_courses', 'CoursePortal::allCourses', ['filter' => 'auth']);
$routes->get('coursemain/my_course', 'CoursePortal::myCourse', ['filter' => 'auth']);
$routes->get('coursemain/detail/(:num)', 'CoursePortal::detail/$1', ['filter' => 'auth']);
$routes->post('coursemain/enroll/(:num)', 'CoursePortal::enroll/$1', ['filter' => 'auth']);
$routes->post('coursemain/start/(:num)', 'CoursePortal::start/$1', ['filter' => 'auth']);
$routes->get('coursemain/lesson/(:num)', 'CoursePortal::lesson/$1', ['filter' => 'auth']);
$routes->post('coursemain/lesson/(:num)/complete', 'CoursePortal::completeLesson/$1', ['filter' => 'auth']);
$routes->get('coursemain/quiz/(:num)', 'QuizPortal::show/$1', ['filter' => 'auth']);
$routes->post('coursemain/quiz/(:num)/submit', 'QuizPortal::submit/$1', ['filter' => 'auth']);
$routes->get('coursemain/survey/(:num)', 'SurveyPortal::show/$1', ['filter' => 'auth']);
$routes->post('coursemain/survey/(:num)/submit', 'SurveyPortal::submit/$1', ['filter' => 'auth']);
$routes->get('scorm/load/(:num)', 'ScormPlayer::load/$1', ['filter' => 'auth']);
$routes->post('scorm/datamodel/(:num)', 'ScormPlayer::datamodel/$1', ['filter' => 'auth']);
$routes->get('certificate/certificateall', 'CertificatePortal::index', ['filter' => 'auth']);
$routes->get('certificate/download/(:num)', 'CertificatePortal::download/$1', ['filter' => 'auth']);
$routes->post('certificate/regenerate/(:num)', 'CertificatePortal::regenerate/$1', ['filter' => 'auth']);
$routes->get('report/learnerReport', 'ReportPortal::learnerReport', ['filter' => 'auth']);
$routes->get('report/learnerReport/export', 'ReportPortal::learnerExport', ['filter' => 'auth']);
$routes->get('report/courseSummary/export', 'ReportPortal::courseSummaryExport', ['filter' => 'auth']);
$routes->get('report/scormTracking/export', 'ReportPortal::scormExport', ['filter' => 'auth']);
$routes->get('report/certificateIssued/export', 'ReportPortal::certificateExport', ['filter' => 'auth']);
$routes->post('dashboard/unlockAcc/(:num)', 'ModulePortal::unlockUser/$1', ['filter' => 'auth']);
$routes->post('dashboard/resetPass/(:num)', 'ModulePortal::resetPassword/$1', ['filter' => 'auth']);
$routes->get('manage/userdata', 'ModulePortal::userIndex', ['filter' => 'auth']);
$routes->get('manage/userdata/create', 'ModulePortal::createUser', ['filter' => 'auth']);
$routes->post('manage/userdata/create', 'ModulePortal::storeUser', ['filter' => 'auth']);
$routes->get('manage/userdata/(:num)/edit', 'ModulePortal::editUser/$1', ['filter' => 'auth']);
$routes->post('manage/userdata/(:num)/update', 'ModulePortal::updateUser/$1', ['filter' => 'auth']);
$routes->post('manage/userdata/(:num)/status', 'ModulePortal::userStatus/$1', ['filter' => 'auth']);
$routes->get('manage/userdata/bulk/template', 'ModulePortal::bulkUserTemplate', ['filter' => 'auth']);
$routes->post('manage/userdata/bulk/import', 'ModulePortal::bulkUserImport', ['filter' => 'auth']);
$routes->post('manage/userdata/bulk/enrollment', 'ModulePortal::bulkEnrollment', ['filter' => 'auth']);
$routes->post('manage/companydata/create', 'ModulePortal::createCompany', ['filter' => 'auth']);
$routes->get('manage/companydata/(:num)/edit', 'ModulePortal::editCompany/$1', ['filter' => 'auth']);
$routes->post('manage/companydata/(:num)/update', 'ModulePortal::updateCompany/$1', ['filter' => 'auth']);
$routes->post('manage/companydata/(:num)/status', 'ModulePortal::companyStatus/$1', ['filter' => 'auth']);
$routes->post('manage/departmentdata/create', 'ModulePortal::createDepartment', ['filter' => 'auth']);
$routes->get('manage/departmentdata/(:num)/edit', 'ModulePortal::editDepartment/$1', ['filter' => 'auth']);
$routes->post('manage/departmentdata/(:num)/update', 'ModulePortal::updateDepartment/$1', ['filter' => 'auth']);
$routes->post('manage/departmentdata/(:num)/status', 'ModulePortal::departmentStatus/$1', ['filter' => 'auth']);
$routes->get('(:segment)', 'ModulePortal::show/$1', ['filter' => 'auth']);
$routes->get('(:segment)/(:any)', 'ModulePortal::show/$1/$2', ['filter' => 'auth']);
