<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= esc($config['path']) ?></title>
<style>body{font-family:Arial;background:#f4f6f8}main{max-width:1250px;margin:25px auto}.panel{background:#fff;padding:20px;margin-bottom:20px;overflow:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}label{display:grid;gap:5px}input,textarea,button{padding:9px}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:8px;border:1px solid #ddd;max-width:260px;overflow-wrap:anywhere}a{color:#b5121b}.ok{color:green}.error{color:#b00020}</style></head><body><main>
<p><a href="<?= site_url('dashboard') ?>">← Dashboard</a></p><h1><?= esc($config['path']) ?></h1>
<?php if(session()->getFlashdata('module_notice')):?><p class="ok"><?= esc(session()->getFlashdata('module_notice')) ?></p><?php endif ?><?php if(session()->getFlashdata('module_error')):?><p class="error"><?= esc(session()->getFlashdata('module_error')) ?></p><?php endif ?>
<?php if($editing||$canAdd): ?><form class="panel" method="post" enctype="multipart/form-data" action="<?= site_url('admin-module/'.$key.'/save') ?>"><?= csrf_field() ?><?php if($editing): ?><input type="hidden" name="<?= esc($config['pk']) ?>" value="<?= esc($editing[$config['pk']]) ?>"><?php endif ?><div class="grid">
<?php foreach($config['fields'] as $field): ?><label><?= esc($field) ?><textarea name="<?= esc($field) ?>" rows="2"><?= esc(old($field,$editing[$field]??'')) ?></textarea><?php if(in_array($field,$config['uploads']??[],true)): ?><input type="file" name="upload__<?= esc($field) ?>" accept=".jpg,.jpeg,.png,.webp,.pdf"><?php endif ?></label><?php endforeach ?></div><p><button type="submit"><?= $editing?'Update':'Create' ?></button><?php if($editing): ?> <a href="<?= site_url($config['path']) ?>">Cancel</a><?php endif ?></p></form><?php endif ?>
<div class="panel"><table><thead><tr><?php foreach(array_slice(array_keys($rows[0]??[$config['pk']=>'']),0,12) as $field): ?><th><?= esc($field) ?></th><?php endforeach ?><th></th></tr></thead><tbody>
<?php foreach($rows as $row): ?><tr><?php foreach(array_slice(array_keys($rows[0]),0,12) as $field): ?><td><?= esc(mb_strimwidth(strip_tags((string)($row[$field]??'')),0,120,'…')) ?></td><?php endforeach ?><td><?php if($canEdit): ?><a href="<?= site_url($config['path']).'?edit='.esc($row[$config['pk']]) ?>">Edit</a><?php endif ?><?php if($key==='questionnaire'): ?> <a href="<?= site_url('questionnaire/'.$row[$config['pk']].'/questions') ?>">Questions</a><?php elseif($key==='public-survey'): ?> <a href="<?= site_url('public-survey/'.$row[$config['pk']].'/questions') ?>">Questions</a><?php endif ?></td></tr><?php endforeach ?></tbody></table></div>
</main></body></html>
