CREATE TABLE IF NOT EXISTS `lms_audit_logs` (
  `audit_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `audit_action` VARCHAR(32) NOT NULL,
  `audit_table` VARCHAR(128) DEFAULT NULL,
  `audit_row_key` VARCHAR(255) DEFAULT NULL,
  `audit_old_values` LONGTEXT DEFAULT NULL,
  `audit_new_values` LONGTEXT DEFAULT NULL,
  `audit_changed_values` LONGTEXT DEFAULT NULL,
  `audit_sql` LONGTEXT DEFAULT NULL,
  `audit_controller` VARCHAR(128) DEFAULT NULL,
  `audit_method` VARCHAR(128) DEFAULT NULL,
  `audit_uri` TEXT DEFAULT NULL,
  `audit_http_method` VARCHAR(16) DEFAULT NULL,
  `audit_ip` VARCHAR(64) DEFAULT NULL,
  `audit_user_agent` TEXT DEFAULT NULL,
  `audit_user_id` VARCHAR(64) DEFAULT NULL,
  `audit_emp_id` VARCHAR(64) DEFAULT NULL,
  `audit_username` VARCHAR(255) DEFAULT NULL,
  `audit_user_display` VARCHAR(255) DEFAULT NULL,
  `audit_created_at` DATETIME NOT NULL,
  PRIMARY KEY (`audit_id`),
  KEY `idx_audit_table_created` (`audit_table`, `audit_created_at`),
  KEY `idx_audit_user_created` (`audit_user_id`, `audit_emp_id`, `audit_created_at`),
  KEY `idx_audit_action_created` (`audit_action`, `audit_created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
