<?php $quiz = $grading['quiz']; ?>
<!doctype html><html lang="th"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= esc($title) ?></title>
<style>
:root{--brand:#e71921;--ink:#1f2937;--muted:#6b7280;--line:#e5e7eb;--bg:#f4f6f9;--panel:#fff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Arial,"Helvetica Neue",sans-serif}a{color:inherit;text-decoration:none}.topbar{background:#fff;border-bottom:1px solid var(--line)}.brand-row{max-width:1120px;margin:0 auto;min-height:74px;display:grid;grid-template-columns:220px 1fr 220px;align-items:center;gap:18px;padding:10px 22px}.brand-mark{font-weight:900;color:var(--brand);font-size:20px}.brand-center{text-align:center;font-size:28px;font-weight:900}.brand-actions{display:flex;justify-content:flex-end;gap:14px;color:var(--muted);font-size:13px}.logout{font-weight:800;color:#111827}.page{max-width:1120px;margin:0 auto;padding:28px 22px 42px}.head{display:flex;justify-content:space-between;gap:16px;align-items:flex-end;margin-bottom:18px}.kicker{color:var(--brand);font-size:12px;font-weight:900;text-transform:uppercase}h1{margin:5px 0 0;font-size:30px}.sub{color:var(--muted);font-size:13px;margin:7px 0 0}.btn{border:1px solid var(--line);background:#fff;border-radius:7px;padding:10px 14px;font-weight:900;cursor:pointer}.btn.primary{background:var(--brand);color:#fff;border-color:var(--brand)}.notice{border:1px solid #bee7cf;background:#ecfdf3;color:#087443;border-radius:8px;padding:12px 14px;margin-bottom:16px;font-weight:800}.error{border:1px solid #ffc7c7;background:#fff1f1;color:#b42318;border-radius:8px;padding:12px 14px;margin-bottom:16px;font-weight:800}.panel{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:18px}.wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:12px 10px;border-bottom:1px solid var(--line);vertical-align:top}th{background:#fafafa;color:var(--muted);font-size:12px;text-transform:uppercase}input,textarea{width:100%;border:1px solid var(--line);border-radius:7px;padding:9px 10px}textarea{min-height:70px}@media(max-width:850px){.brand-row{grid-template-columns:1fr}.brand-center,.brand-actions{text-align:left;justify-content:flex-start}.head{display:block}.head .btn{margin-top:12px}}
</style>
    <link href="<?= base_url('css/enterprise-pages.css?v=20260701-2') ?>" rel="stylesheet"></head><body><header class="topbar"><div class="brand-row"><a class="brand-mark" href="<?= site_url('dashboard') ?>">LMS CI4</a><div class="brand-center">E-LEARNING</div><div class="brand-actions"><span><?= esc($name ?? '-') ?></span><a class="logout" href="<?= site_url('logout') ?>">Logout</a></div></div></header><main class="page">
<?php if (session()->getFlashdata('course_notice')): ?><div class="notice"><?= esc(session()->getFlashdata('course_notice')) ?></div><?php endif; ?><?php if (session()->getFlashdata('course_error')): ?><div class="error"><?= esc(session()->getFlashdata('course_error')) ?></div><?php endif; ?>
<div class="head"><div><div class="kicker"><?= esc($title_main ?: 'Manage Course') ?></div><h1><?= esc($quiz['title']) ?></h1><p class="sub"><?= esc(($quiz['ccode'] ?: '-') . ' - ' . ($quiz['course_title'] ?? '-')) ?></p></div><a class="btn" href="<?= site_url('managecourse/quizzes/' . $quiz['qiz_id'] . '/edit') ?>">Edit Quiz</a></div>
<section class="panel"><div class="wrap"><table><thead><tr><th>Learner</th><th>Question</th><th>Answer</th><th>Score</th><th>Grade</th></tr></thead><tbody>
<?php foreach (($grading['rows'] ?? []) as $row): ?><tr><td><?= esc(($row['emp_c'] ?: '-') . ' ' . ($row['learner_name'] ?: '')) ?><br><span class="sub"><?= esc($row['tc_finish']) ?></span></td><td><?= esc($row['question_title']) ?><br><span class="sub">Max <?= esc($row['ques_score']) ?></span></td><td><?= nl2br(esc($row['tc_answer'])) ?></td><td><?= esc($row['tc_score']) ?></td><td><form method="post" action="<?= site_url('managecourse/quiz-answers/' . $row['tc_id'] . '/grade') ?>"><input type="number" step="0.01" min="0" max="<?= esc($row['ques_score']) ?>" name="tc_score" value="<?= esc($row['tc_score']) ?>"><textarea name="tc_note" placeholder="Grading note"><?= esc($row['tc_note']) ?></textarea><button class="btn primary" type="submit">Save</button></form></td></tr><?php endforeach; ?>
<?php if (empty($grading['rows'])): ?><tr><td colspan="5">No text answers to grade.</td></tr><?php endif; ?></tbody></table></div></section>
</main>    <script src="<?= base_url('js/enterprise-pages.js?v=20260701-3') ?>"></script>
</body></html>
